apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
spec:
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: demo-voting-app
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
           - containerPort: 80
